name: Run with defaults

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run cookiecutter with defaults
        uses: andrewthetechie/gha-cookiecutter@main
        with:
          # path to what you checked out
          template: ./
          outputDir: ./_generated
          cookiecutterValues: '{}'
