name: Run with defaults

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  default_arguments:
    name: Run cookiecutter with defaults 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.11
      # - name: Run cookiecutter
      #   uses: andrewthetechie/gha-cookiecutter@main
      #   with:
      #     template: ./
      #     outputDir: ./_generated
      #     cookiecutterValues: '{
      #       "project_name": "MyProject",
      #       "minimal_python_version": "3.11"
      #     }'
      - name: Run cookiecutter
        run: |
            pip install cookiecutter
            cookiecutter . --no-input project_name="MyProject" minimal_python_version="3.11" -o ./_generated 
      - name: List files in the repository
        run: |
            tree ./_generated
      - name: Make install new package
        run: |
            # cd ./_generated/MyProject
            python3.11 -m venv ./venv
